# --- Сервер 1: Обрабатывает домен фронтенда ---
# Он раздает статические файлы React/Vue приложения.
server {
  listen 80;
  # На этапе деплоя здесь будет указан реальный домен.
  server_name i-bocharov-project.nomorepartiessbs.ru;

  # Конфигурация для раздачи статических файлов.
  location / {
    root /usr/share/nginx/html;
    index index.html;
    # Директива `try_files` необходима для корректной работы роутинга в SPA.
    # Все запросы к несуществующим файлам перенаправляются на index.html.
    try_files $uri $uri/ /index.html;
  }

  # Стандартная обработка серверных ошибок.
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}

# --- Сервер 2: Обрабатывает домен API ---
# Он проксирует АБСОЛЮТНО ВСЕ запросы на сервис бэкенда.
server {
  listen 80;
  server_name api.i-bocharov-project.nomorepartiessbs.ru;

  # Проксируем все запросы (`/`) на NestJS-приложение.
  location / {
    # `backend` - это имя сервиса в docker-compose.yml.
    proxy_pass http://backend:3000/;
    # Установка заголовков для корректной передачи информации о запросе.
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}